"""ingest tables

Revision ID: daa3ba6946b9
Revises: 
Create Date: 2026-10-02 16:17:04.776505

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa3ba6946b9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.String(length=64), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('raw_file_path', sa.String(length=512), nullable=True),
    sa.Column('intervals_icu_load', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_activity_source_source_id')
    )
    op.create_table('wellness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv', sa.Float(), nullable=True),
    sa.Column('ln_hrv', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_wellness_athlete_date')
    )
    op.create_table('activity_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('stream_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'stream_type', name='uq_activity_stream_type')
    )
    op.create_index(op.f('ix_activity_stream_activity_id'), 'activity_stream', ['activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_stream_activity_id'), table_name='activity_stream')
    op.drop_table('activity_stream')
    op.drop_table('wellness')
    op.drop_table('activity')
    # ### end Alembic commands ###
