"""Rolling-summary conversation memory policy (WA-8, brief §9.2).

**What is the SDK's and what is ours** (ODD task, "Agent runtime" table):
conversation persistence is the SDK's (``RepositorySessionManager`` + our
``SessionRepository``, :mod:`app.agent.session_store`); the message
restoration, per-message persistence, agent-state sync and the
``ConversationManager`` extension point are all SDK machinery. OURS is
the rolling-summary POLICY implemented as a
:class:`strands.agent.conversation_manager.ConversationManager` subclass —
the same extension point the SDK's own ``SummarizingConversationManager``
uses:

- The **last N turns stay verbatim** (``window_size`` messages);
  everything older is folded into a stored **rolling summary**.
- The summary is generated ONCE when the OWNER-CHOICE threshold is
  crossed (``trigger_messages`` not-yet-summarized messages have aged
  past the window) and then **reused verbatim** — it is never
  regenerated on every message. Between crossings the next turns see the
  stored summary unchanged.
- The summary is generated by a REAL model invocation (the SDK's own
  summarization prompt and stream processor, mirroring the SDK's
  ``SummarizingConversationManager._generate_summary_with_model``), and
  its token usage is captured (``generated_summaries``) so the pipeline
  can count it against the conversation budget and persist it with the
  turn's provenance (``agent_conversation_summary``).

**Persistence**: the summary lives in the SDK's conversation-manager
state (``get_state``/``restore_from_session``), which the SDK's session
manager syncs into the database after every message and every invocation
— so it survives process boundaries like the rest of the conversation.
The SDK mechanism this relies on: after ``apply_management`` collapses
history, ``removed_message_count`` records how many ORIGINAL messages
were folded away; on restore the SDK prepends the summary message and
lists the session's messages with that offset (the summarized prefix is
skipped, never deleted).

**Where the SDK interface forced our hand** (recorded honestly): the SDK's
``generate_summary`` helper discards the invocation's token usage, and the
budget contract (WA-8) needs it — so the summary call mirrors the SDK's
helper via the SDK's own ``process_stream`` and ``as_user_summary`` while
keeping the usage. ``apply_management`` is synchronous by SDK contract and
runs inside the pipeline's event loop, so the async model call is bridged
exactly the way the SDK's own summarizing manager does it
(``strands._async.run_async``).
"""

from __future__ import annotations

import logging
from typing import Any

from strands.agent.conversation_manager import ConversationManager
from strands.agent.conversation_manager.compression.context_compression import (
    DEFAULT_SUMMARIZATION_PROMPT,
    adjust_split_point_for_tool_pairs,
    as_user_summary,
)
from strands.event_loop.streaming import process_stream
from strands.types.content import Message
from strands.types.exceptions import ContextWindowOverflowException

logger = logging.getLogger(__name__)

__all__ = ["RollingSummaryConversationManager"]


class RollingSummaryConversationManager(ConversationManager):
    """Keep the last N messages verbatim; fold older turns into a stored
    summary that is regenerated only when the trigger threshold recrosses.

    Args:
        window_size: Number of most-recent messages kept verbatim (the
            ``AGENT_MEMORY_WINDOW_MESSAGES`` setting).
        trigger_messages: A new summary is generated only when at least
            this many not-yet-summarized messages have aged past the
            window since the last summary (the
            ``AGENT_SUMMARY_TRIGGER_MESSAGES`` setting).
        summarization_system_prompt: Optional override; defaults to the
            SDK's ``DEFAULT_SUMMARIZATION_PROMPT``.

    Attributes:
        removed_message_count: Original conversation messages folded into
            the summary (the SDK's offset contract for session restore).
        generated_summaries: One entry per summary this manager generated
            (``summary`` text, ``usage`` token dict, ``covered_messages``),
            consumed by the pipeline for budget accounting and audit
            persistence.
        summary_text: The current summary's text (None until first fold).
    """

    def __init__(
        self,
        *,
        window_size: int,
        trigger_messages: int,
        summarization_system_prompt: str | None = None,
    ) -> None:
        super().__init__()
        if window_size <= 0:
            raise ValueError(f"window_size must be positive, got {window_size!r}")
        if trigger_messages <= 0:
            raise ValueError(
                f"trigger_messages must be positive, got {trigger_messages!r}"
            )
        self.window_size = window_size
        self.trigger_messages = trigger_messages
        self.summarization_system_prompt = summarization_system_prompt
        self._summary_message: Message | None = None
        self.generated_summaries: list[dict[str, Any]] = []

    # --- SDK restore/state contract -----------------------------------------

    def restore_from_session(self, state: dict[str, Any]) -> list[Message] | None:
        """Restore the folded-turn count and the stored summary; the SDK
        prepends the returned summary message ahead of the restored
        messages."""
        super().restore_from_session(state)  # validates __name__, restores the offset
        self._summary_message = state.get("summary_message")
        return [self._summary_message] if self._summary_message else None

    def get_state(self) -> dict[str, Any]:
        """State persisted by the SDK's session manager (carries the
        summary across process boundaries)."""
        return {
            "__name__": type(self).__name__,
            "removed_message_count": self.removed_message_count,
            "summary_message": self._summary_message,
        }

    # --- SDK management hooks ---------------------------------------------------

    def apply_management(self, agent: Any, **kwargs: Any) -> None:
        """Called by the SDK once per completed invocation: collapse the
        history if the trigger threshold has been crossed."""
        self._collapse(agent, ignore_trigger=False)

    def reduce_context(self, agent: Any, e: Exception | None = None, **kwargs: Any) -> None:
        """SDK overflow recovery: force a collapse (ignoring the trigger);
        if there is not enough history to summarize, trim the oldest
        messages down to the window so the next model call can proceed."""
        try:
            before = len(agent.messages)
            self._collapse(agent, ignore_trigger=True)
            if len(agent.messages) == before:
                self._trim_to_window(agent)
        except ContextWindowOverflowException:
            self._trim_to_window(agent)

    # --- The rolling-summary policy ----------------------------------------------

    @property
    def summary_text(self) -> str | None:
        """The current summary's text (None until the first fold)."""
        if self._summary_message is None:
            return None
        return "".join(
            block.get("text", "")
            for block in self._summary_message.get("content", [])
            if "text" in block
        )

    def _collapse(self, agent: Any, *, ignore_trigger: bool) -> None:
        """Fold every turn older than the window into the stored summary.

        Keeps the last ``window_size`` messages verbatim; the folded range
        (plus any previous summary) is summarized by one model invocation.
        """
        had_summary = self._summary_message is not None
        base = 1 if had_summary else 0
        # Original messages seen so far = folded away + still in the list
        # (minus the summary message itself, which is not an original turn).
        original_total = self.removed_message_count + len(agent.messages) - base
        eligible_total = original_total - self.window_size
        if eligible_total <= 0:
            return
        new_eligible = eligible_total - self.removed_message_count
        if not ignore_trigger and new_eligible < self.trigger_messages:
            return  # below the threshold: REUSE the stored summary unchanged

        split = len(agent.messages) - self.window_size
        if split <= base:
            return
        try:
            # Never break a toolUse/toolResult pair at the boundary (the
            # SDK's own split-point guard).
            split = adjust_split_point_for_tool_pairs(agent.messages, split)
        except ContextWindowOverflowException:
            return
        to_summarize = agent.messages[:split]

        model = getattr(agent, "aux_model", None) or agent.model
        summary_message, usage = _run_async(
            lambda: summarize_with_usage(
                to_summarize,
                model,
                system_prompt=self.summarization_system_prompt,
            )
        )
        summary_text = "".join(
            block.get("text", "")
            for block in summary_message.get("content", [])
            if "text" in block
        )
        self._summary_message = summary_message
        # Same accounting as the SDK's SummarizingConversationManager: the
        # folded range includes the previous summary message, which is not
        # an original turn.
        self.removed_message_count += len(to_summarize) - base
        agent.messages[:] = [summary_message, *agent.messages[split:]]
        self.generated_summaries.append(
            {
                "summary": summary_text,
                "usage": usage,
                "covered_messages": self.removed_message_count,
            }
        )
        logger.info(
            "conversation summary regenerated: covered_messages=<%d>, "
            "usage_total_tokens=<%s>",
            self.removed_message_count,
            usage.get("totalTokens"),
        )

    def _trim_to_window(self, agent: Any) -> None:
        """Last-resort overflow recovery: drop (not summarize) the oldest
        messages beyond the window, keeping tool pairs intact."""
        split = len(agent.messages) - self.window_size
        if split <= 0:
            return
        split = adjust_split_point_for_tool_pairs(agent.messages, split)
        dropped = agent.messages[:split]
        self.removed_message_count += len(dropped) - (1 if self._summary_message else 0)
        del agent.messages[:split]
        logger.warning(
            "conversation memory trimmed (overflow recovery): dropped_messages=<%d>",
            len(dropped),
        )


# --- Summary generation (mirrors the SDK's own summarizer) -------------------


async def summarize_with_usage(
    messages: list[Message],
    model: Any,
    *,
    system_prompt: str | None = None,
) -> tuple[Message, dict[str, Any]]:
    """Summarize ``messages`` with one model invocation and CAPTURE its usage.

    Mirrors the SDK's ``generate_summary`` (same summarization prompt, same
    ``process_stream`` consumption, same ``as_user_summary`` re-role) with
    one addition the SDK helper lacks: the invocation's token usage, which
    WA-8 counts against the conversation budget and persists.
    """
    resolved_system_prompt = (
        system_prompt if system_prompt is not None else DEFAULT_SUMMARIZATION_PROMPT
    )
    summarization_messages = [
        *messages,
        {"role": "user", "content": [{"text": "Please summarize this conversation."}]},
    ]

    chunks = model.stream(
        summarization_messages,
        tool_specs=None,
        system_prompt=resolved_system_prompt,
    )
    usage: dict[str, Any] = {}
    result_message: Message | None = None
    async for event in process_stream(chunks):
        if "stop" in event:
            _, result_message, usage, _ = event["stop"]
    if result_message is None:
        raise RuntimeError("Failed to generate summary: no response from model")
    if not isinstance(usage, dict):
        usage = usage.model_dump()  # pydantic Usage -> plain dict
    return as_user_summary(result_message), usage


def _run_async(async_func: Any) -> Any:
    """Bridge an async call from the SDK's synchronous ``apply_management``.

    Same pattern as the SDK's own ``SummarizingConversationManager``
    (``strands._async.run_async``): run on a separate thread/event loop so
    it works from inside the pipeline's running event loop.
    """
    from strands._async import run_async

    return run_async(async_func)
